config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :bills
  get 'bill/pay', to: "bills#pay"
  post 'bill/pay', to: "bills#pay"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bill.rb
class Bill < ApplicationRecord

  def self.getAccountDetails
    require "json"

    domain = Rails.application.secrets.ZUORA_API_DOMAIN
    endpoint = domain + '/v1/accounts/A00000029'
    puts endpoint
    usrname = Rails.application.secrets.ZUORA_USERNAME
    pass = Rails.application.secrets.ZUORA_PASSWORD

    auth1 = usrname + ':' + pass
    auth1_enc = "Basic " + Base64.encode64(auth1).strip


    auth_header = {"Content-Type" => "application/json", "Cache-Control" => "no-cache", "Authorization" => auth1_enc}
    puts auth_header

    begin
      #TODO try to force api call failure and handle it here
      response = HTTParty.get( endpoint, :headers => auth_header)

    rescue Exception=> e
      puts e
      puts response
    end

    begin
      parsed = JSON.parse(response.body)
    rescue JSON::ParserError
      result=1
      parsed = {success: "false", error: {message: "Could not retrieve JSON response", code: "CUSTOM"}}
    end

    #result = JSON.unparse(response)
    puts response.body
    #Rails.logger.info(JSON.unparse(response))
    #
    return parsed

  end

  class Source
    attr_reader :type, :number, :expiry_month, :expiry_year, :name, :cvv
    attr_writer :type, :number, :expiry_month, :expiry_year, :name, :cvv

    def getJSON
      payload={}
      payload[:type] = type
      payload[:number] = number
      payload[:expiry_month] = expiry_month
      payload[:expiry_year] = expiry_year
      payload[:name] = name
      payload[:cvv] = cvv

      return payload
    end
  end

  class CKO_Pay
    attr_reader :source, :amount, :currency, :reference
    attr_writer :source, :amount, :currency, :reference

    def getJSON
      payload={}
      payload["source"]= source
      payload[:amount] = amount
      payload[:currency] = currency
      payload[:reference] = reference

      return payload
    end
  end

  def self.createPayment(param)
    puts param["cvv"]
    source = Source.new
    source.type = param["type"]
    source.number = param["number"]
    source.expiry_month = param["expiry_month"]
    source.expiry_year = param["expiry_year"]
    source.name = param["name"]
    source.cvv = param["cvv"]

    ckop = CKO_Pay.new
    ckop.source = source.getJSON
    ckop.amount = param["amount"]
    ckop.currency = param["currency"]
    ckop.reference = param["reference"]

    post_body = JSON.unparse(ckop.getJSON)

    domain = Rails.application.secrets.CKO_API_DOMAIN
    endpoint = domain + '/payments'
    auth = Rails.application.secrets.CKO_WEB_SK
    auth_header = {"Content-Type" => "application/json", "Cache-Control" => "no-cache", "Authorization" => auth}

    puts post_body

    begin
      #TODO try to force api call failure and handle it here
      response = HTTParty.post(endpoint, :headers => auth_header, :body => post_body)
    rescue Exception=> e
      puts e
    end

    #puts response.body
    response = JSON.parse(response.body)
    puts response
    puts 'RES::'
    if response["approved"] == true
      result ={}
      result["approved"] = true
      result["response_summary"] = response["response_summary"]
      puts result
      return result
    else
      result ={}
      result["approved"] = false
      result["response_summary"] = response["response_summary"]
      result["error_type"] = response["error_type"]
      result["error_codes"] = response["error_codes"]
      puts result
      return result
    end
  end

  def self.createCreditMemo(amount)
    payload='{
    "accountId": "2c92c0fa6c8aee2e016c8cb747e90a4d",
    "autoPost": true,
    "charges": [
        {
            "chargeId": "2c92c0f86a2f3322016a30d5e11b2682",
            "memoItemAmount": AMOUNT
        }
    ],
    "comment": "Check",
    "effectiveDate": "2020-07-21",
    "reasonCode": "Ad hoc credit"
}'
    post_body = payload.sub("AMOUNT",amount)

    domain = Rails.application.secrets.ZUORA_API_DOMAIN
    endpoint = domain + '/v1/creditmemos'
    puts endpoint
    usrname = Rails.application.secrets.ZUORA_USERNAME
    pass = Rails.application.secrets.ZUORA_PASSWORD

    auth1 = usrname + ':' + pass
    auth1_enc = "Basic " + Base64.encode64(auth1).strip

    auth_header = {"Content-Type" => "application/json", "Cache-Control" => "no-cache", "Authorization" => auth1_enc}
    puts auth_header

    begin
      #TODO try to force api call failure and handle it here
      response = HTTParty.post( endpoint, :headers => auth_header, :body => post_body)

    rescue Exception=> e
      puts e
      puts response
    end

    puts response.body
    response = JSON.parse(response.body)
    puts response
    if response["status"] == "Posted"
      return true
    else
      return false
    end

  end

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: %i[ show edit update destroy ]

  # GET /bills or /bills.json
  def index
    @accountSuccess = Bill.getAccountDetails["success"]
    @accountDetails = Bill.getAccountDetails
    #@bills = Bill.all
  end

  def pay
    @paymentResponse = {}
    if params["type"] == 'card'
      @paymentResponse = Bill.createPayment(params)
      if @paymentResponse["approved"] == true
        @invoicePaid = Bill.createCreditMemo(params["amount"])
        if @invoicePaid == true
          @invoicePaidAmount = params["amount"]
        end
      end
    end
    puts params
  end

  # GET /bills/1 or /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills or /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: "Bill was successfully created." }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1 or /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: "Bill was successfully updated." }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1 or /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: "Bill was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bill_params
      params.fetch(:bill, {})
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= form_for(bill) do |f| %>
  <% if bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bills</h1>

<% if @accountSuccess == true%>
<table border="solid 0.5px;">
  <tr>
    <th>Name</th>
    <th>Account Number</th>
    <th>Balance</th>
  </tr>
  <tr>
    <td> <%=@accountDetails["basicInfo"]["name"]%> </td>
    <td><%=@accountDetails["basicInfo"]["accountNumber"]%></td>
    <td><%=@accountDetails["metrics"]["balance"]%></td>
  </tr>
</table>
 <!-- <%#= @accountDetails%>-->
  <%else %>
  <p>No Account info</p>
  <%end %>

<p><%= link_to "Make Payment", {:action => 'pay' }%></p>




<!--<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <%# @bills.each do |bill| %>
      <tr>
        <td><%#= link_to 'Show', bill %></td>
        <td><%#= link_to 'Edit', edit_bill_path(bill) %></td>
        <td><%#= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Bill', new_bill_path %>-->

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Back', bills_path %>

app/views/bills/pay.html.erb
<% if @paymentResponse["approved"].nil?%>
  <p>Pay your bills!</p>
  <%else%>
  <div>Payment Status:</div>
  <div><%=@paymentResponse["response_summary"]%></div>
  <div><%=@paymentResponse["error_type"]%></div>
  <div><%=@paymentResponse["error_codes"]%></div>
    <%if @invoicePaid == true %>
    <div> USD <%=@invoicePaidAmount %> is successfully paid towards your Invoice/Account Balance!</div>
    <%end %>
<%end %>

<p><%= link_to "Dashboard", {:action => 'index' }%></p>

<table>

<%= form_tag("/bill/pay", :method => "post") do %>
    <tr>
      <td>
        <%=label_tag(:type, "Type:") %>
        <%=text_field_tag(:type, 'card', readonly: true) %>
      </td>
    </tr>
    <tr>
      <td>
      <%=label_tag(:number, "number:") %>
        <%=text_field_tag(:number, nil, minlength: 16 ,maxlength: 16, value: '5199992312641465', required: true) %>
    </td>
    </tr>
    <tr>
      <td>
        <%=label_tag(:expiry_month, "expiry_month:") %>
        <%=text_field_tag(:expiry_month, nil, minlength: 1, maxlength: 2, value: '12', required: true) %>
      </td>
    </tr>

    <tr>
      <td>
        <%=label_tag(:expiry_year, "expiry_year:") %>
        <%=text_field_tag(:expiry_year, nil, minlength: 4, maxlength: 4, value: '2027', required: true) %>
      </td>
    </tr>

    <tr>
      <td>
        <%=label_tag(:name, "name:") %>
        <%=text_field_tag(:name, nil, minlength: 2, maxlength: 22, value: 'Jane Doe', required: true) %>
      </td>
    </tr>

    <tr>
      <td>
        <%=label_tag(:cvv, "cvv:") %>
        <%=text_field_tag(:cvv, nil, minlength: 3, maxlength: 3, value: '010', required: true) %>
      </td>
    </tr>

    <tr>
      <td>
        <%=label_tag(:amount, "amount:") %>
        <%=text_field_tag(:amount, nil, maxlength: 10, required: true) %>
      </td>
    </tr>
    <tr>
      <td>
        <%=label_tag(:currency, "currency:") %>
        <%=text_field_tag(:currency, nil, maxlength: 4, value: 'USD', readonly: true) %>
      </td>
    </tr>
    <tr>
      <td>
        <%=label_tag(:reference, "reference:") %>
        <%=text_field_tag(:reference, nil, maxlength: 20, value: 'ord-001') %>
      </td>
    </tr>

      <tr>
        <td>
          <%= submit_tag("PAY")%>
        </td>
      </tr>
<% end %>
</table>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>